# [START runtime]
runtime: nodejs12
# [END runtime]

# [START handlers]
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
# handlers:
# - url: /
#   static_files: build/index.html
#   upload: build/index.html
# - url: /
#   static_dir: build
#   http_headers:
#     Access-Control-Allow-Origin: "*"
# - url: /.*
#   script: auto
#   secure: always
# [END handlers]
